default: &default
  adapter: postgresql
  encoding: utf8
  charset: utf8
  collation: ja_JP.UTF-8
  template: template0
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: <%= Rails.application.secrets.database_master[:host] %>
  username: <%= Rails.application.secrets.database_master[:username] %>
  password: <%= Rails.application.secrets.database_master[:password] %>
  database: <%= Rails.application.secrets.try(:database) || 'vertex_diva_develop' %>
  slave: &default_slave
    host: <%= Rails.application.secrets.database_slave[:host] %>
    username: <%= Rails.application.secrets.database_slave[:username] %>
    password: <%= Rails.application.secrets.database_slave[:password] %>

test:
  <<: *default
  host: <%= Rails.application.secrets.database_master[:host] %>
  username: <%= Rails.application.secrets.database_master[:username] %>
  password: <%= Rails.application.secrets.database_master[:password] %>
  database: vertex_diva_test
  slave: &default_slave
    host: <%= Rails.application.secrets.database_slave[:host] %>
    username: <%= Rails.application.secrets.database_slave[:username] %>
    password: <%= Rails.application.secrets.database_slave[:password] %>

staging:
  <<: *default
  host: <%= Rails.application.secrets.database_master[:host] %>
  username: <%= Rails.application.secrets.database_master[:username] %>
  password: <%= Rails.application.secrets.database_master[:password] %>
  database: vertex_diva_staging
  slave: &default_slave
    host: <%= Rails.application.secrets.database_slave[:host] %>
    username: <%= Rails.application.secrets.database_slave[:username] %>
    password: <%= Rails.application.secrets.database_slave[:password] %>

production:
  <<: *default
  host: <%= Rails.application.secrets.database_master[:host] %>
  username: <%= Rails.application.secrets.database_master[:username] %>
  password: <%= Rails.application.secrets.database_master[:password] %>
  database: vertex_diva_production
  slave: &default_slave
    host: <%= Rails.application.secrets.database_slave[:host] %>
    username: <%= Rails.application.secrets.database_slave[:username] %>
    password: <%= Rails.application.secrets.database_slave[:password] %>
