default: &default
  adapter: postgresql
  encoding: utf8
  charset: utf8
  collation: ja_JP.UTF-8
  template: template0
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: <%= Rails.application.secrets.database_master[:host] %>
  username: <%= Rails.application.secrets.database_master[:username] %>
  password: <%= Rails.application.secrets.database_master[:password] %>
  database: <%= Rails.application.secrets.try(:database) || 'csv_develop' %>
  slave: &default_slave
    host: <%= Rails.application.secrets.database_slave[:host] %>
    username: <%= Rails.application.secrets.database_slave[:username] %>
    password: <%= Rails.application.secrets.database_slave[:password] %>

test:
  <<: *default
  host: <%= Rails.application.secrets.database_master[:host] %>
  username: <%= Rails.application.secrets.database_master[:username] %>
  password: <%= Rails.application.secrets.database_master[:password] %>
  database: csv_test
  slave: &default_slave
    host: <%= Rails.application.secrets.database_slave[:host] %>
    username: <%= Rails.application.secrets.database_slave[:username] %>
    password: <%= Rails.application.secrets.database_slave[:password] %>

staging:
  <<: *default
  host: ec2-107-21-218-93.compute-1.amazonaws.com
  username: rdyvmgeepwcsyg
  password: HNDHODZxxrxV0DTGuF0vzMTorz
  database: d6i65a0v2g0m5j
  slave: &default_slave
    host: ec2-107-21-218-93.compute-1.amazonaws.com
    username: rdyvmgeepwcsyg
    password: HNDHODZxxrxV0DTGuF0vzMTorz

production:
  <<: *default
  host: ec2-107-21-218-93.compute-1.amazonaws.com
  username: rdyvmgeepwcsyg
  password: HNDHODZxxrxV0DTGuF0vzMTorz
  database: d6i65a0v2g0m5j
  slave: &default_slave
    host: ec2-107-21-218-93.compute-1.amazonaws.com
    username: rdyvmgeepwcsyg
    password: HNDHODZxxrxV0DTGuF0vzMTorz
